# Generated by Django 3.0.5 on 2020-04-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=5000)),
                ('nota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechaLanzamiento', models.IntegerField()),
                ('descripcion', models.CharField(max_length=1000)),
                ('categoria', models.CharField(max_length=100)),
                ('portada', models.CharField(max_length=100)),
                ('numeroJugadores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('valor', models.BooleanField()),
                ('critica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerucos.Critica')),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.CharField(max_length=1000)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerucos.Videojuego')),
            ],
        ),
        migrations.CreateModel(
            name='EnlaceCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.CharField(max_length=100)),
                ('enlace', models.CharField(max_length=1000)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerucos.Videojuego')),
            ],
        ),
        migrations.AddField(
            model_name='critica',
            name='videojuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerucos.Videojuego'),
        ),
        migrations.AddField(
            model_name='critica',
            name='videojuegoRespondido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamerucos.Critica'),
        ),
    ]
