# Generated by Django 3.0.5 on 2020-04-22 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamerucos', '0004_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='categoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gamerucos.Categoria'),
        ),
    ]
