# Generated by Django 3.0.5 on 2020-04-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerucos', '0005_auto_20200422_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
    ]
