# Generated by Django 3.0.5 on 2020-04-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerucos', '0006_auto_20200422_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
