# Generated by Django 3.0.5 on 2020-04-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerucos', '0008_remove_videojuego_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
