# Generated by Django 3.0.5 on 2020-04-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamerucos', '0010_auto_20200422_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerucos.Categoria'),
        ),
    ]
