# Generated by Django 3.0.5 on 2020-05-02 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamerucos', '0012_auto_20200423_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
